export const PREFERNCE_CREATE_REQUEST = 'PREFERNCE_CREATE_REQUEST';
export const PREFERNCE_CREATE_SUCCESS = 'PREFERNCE_CREATE_SUCCESS';
export const PREFERNCE_CREATE_FAIL = 'PREFERNCE_CREATE_FAIL';

export const PREFERNCE_LIST_REQUEST = 'PREFERNCE_LIST_REQUEST';
export const PREFERNCE_LIST_SUCCESS = 'PREFERNCE_LIST_SUCCESS';
export const PREFERNCE_LIST_FAIL = 'PREFERNCE_LIST_FAIL';

export const PREFERNCE_DETAILS_REQUEST = 'PREFERNCE_DETAILS_REQUEST';
export const PREFERNCE_DETAILS_SUCCESS = 'PREFERNCE_DETAILS_SUCCESS';
export const PREFERNCE_DETAILS_FAIL = 'PREFERNCE_DETAILS_FAIL';